import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import LoginBtn from "./LoginBtn";
import LogoutBtn from "./LogoutBtn";
import DarkMode from "./DarkMode";
import { cookies } from "next/headers";

import { authOptions } from "/pages/api/auth/[...nextauth].js";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "hihappyj",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let cookie = cookies().get("mode");
  let session = await getServerSession(authOptions);
  //console.log("layout세션", session);
  //console.log(session.user.name);

  return (
    <html lang="en">
      <body className={cookie != undefined && cookie?.value == "dark" ? "dark-mode" : ""}>
        <div className="navbar">
          <Link href="/" className="logo">
            Home
          </Link>
          <Link href="/mongodb-list">할일</Link>
          <Link href="/mongodb-done">완료</Link>
          {session ? (
            <span>
              <Link href="/mongodb-write">등록</Link>
              {session.user.name}
              <LogoutBtn />
            </span>
          ) : (
            <LoginBtn />
          )}
          <DarkMode darkMode={cookie} />
        </div>
        {children}
      </body>
    </html>
  );
}
